<?php
/**
 * Created by PhpStorm.
 * User: laravel-vaance.com
 * Date: 01.10.18
 * Time: 20:27
 */

namespace Modules\Platform\Core\Http\Requests;

use App\Http\Requests\Request;
use Illuminate\Contracts\Validation\Validator;

class CsvImportRequest extends Request
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'csv_file' => 'required|file|mimes:csv,txt',
        ];
    }

    public function failedValidation(Validator $validator)
    {
        flash($validator->errors()->first())->error();
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
