<?php

namespace Modules\Platform\Companies\Repositories;

use Modules\Platform\Companies\Entities\Company;
use Modules\Platform\Companies\Entities\CompanyPlan;
use Modules\Platform\Core\Repositories\PlatformRepository;


/**
 * Class CompanyRepository
 * @package Modules\Platform\Companies\Repositories
 */
class CompanyRepository extends PlatformRepository
{
    public function model()
    {
        return Company::class;
    }

    /**
     * Get companies that has plan
     *
     * @param CompanyPlan $companyPlan
     * @return mixed
     */
    public function getCompaniesWithPlan(CompanyPlan $companyPlan){

        return $this->findWhere([
            'plan_id' => $companyPlan->id
        ]);

    }

    public function update(array $attributes, $id)
    {
        if ($attributes['user_limit'] == '') {
            $attributes['user_limit'] = null;
        }

        if ($attributes['storage_limit'] == '') {
            $attributes['storage_limit'] = null;
        }


        return parent::update($attributes, $id); // TODO: Change the autogenerated stub
    }

    public function create(array $attributes)
    {
        if ($attributes['user_limit'] == '') {
            $attributes['user_limit'] = null;
        }

        if ($attributes['storage_limit'] == '') {
            $attributes['storage_limit'] = null;
        }


        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
